### ISSUE TITLE
Fails with symlinks

### ISSUE THREAD

**Issue by peter-mogensen** [FiloSottile/gvt#12]
Projects can contain internal relative symlinks and work fine with go get.
(example: https://github.com/valyala/ybc)

However, the current file handling code skips symlinks when copying - breaking otherwise fine working go-getable Go packages.

I think I have a small patch to make it work, but those knowing github.com/constabulary/gb and how it's vendored into gvt could probably make a more general patch.

**Comment by FiloSottile** [comment]
Yeah, this broke my vendor/ tests with a couple projects, too.

The background is at constabulary/gb#184, I'll submit a PR to fix it upstream, since now Copyfile is in filepath, which gvt vendors.

**Comment by peter-mogensen** [comment]
I think I have a primitive fix in my fork.
It doesn't handle file permissions perfect when copying from /tmp to the 
vendor dir though.

/Peter

**Comment by FiloSottile** [comment]
I submitted a banal patch to gb, now waiting on Dave.
