### ISSUE TITLE
Shallow and narrow git clone

### ISSUE THREAD

**Issue by bboreham** [FiloSottile/gvt#13]
Currently, gvt does a `git clone` of the whole repo, followed by a `git checkout` of the desired branch.

Could you do `git clone --branch xxx --depth 1` instead, to fetch just the version required?

It seems the current behaviour stems from https://github.com/constabulary/gb/issues/219, but gvt is downloading into a temp directory so shouldn't need that behaviour?

**Comment by dcelasun** [comment]
Yes, this would significantly speed up fetching dependencies. Any thoughts @FiloSottile?

**Comment by FiloSottile** [comment]
My understanding of the problem in constabulary/gb#219 is that when you want to get to a specific revision, there's no way of checking it out with `--branch XXX --depth 1` unless it has a tag on it.

So I think the best we can do is
- use `--branch XXX --depth 1` if `-tag` is used
- use `--branch XXX` unless a naked `-rev` is used

Correct?

**Comment by dcelasun** [comment]
Yes, I think that's correct.

**Comment by FiloSottile** [comment]
Oh, also we can use `--branch XXX --depth 1` in `fetch` (but not `restore`) if no `-rev` is used.

Complete logic:
- if we have a tag name `--branch XXX --depth 1`
- if we have a revision and nothing else, full clone
- if we have a branch name and a revision, `--branch XXX`
- if we have only a branch name `--branch XXX --depth 1`

This should actually speed up most cases. Will do.
