### ISSUE TITLE
.travis.yml file doesn't set GO15VENDOREXPERIMENT=1 

### ISSUE THREAD

**Issue by tleyden** [FiloSottile/gvt#15]
I just took a look at https://github.com/FiloSottile/gvt/blob/master/.travis.yml to see an example of how this is being set, but it looks like it's not being set at all.

Any reason for that?

Here's how it's being set in camlistore: https://github.com/camlistore/camlistore/blob/master/.travis.yml#L13

**Comment by tleyden** [comment]
Here's another example, where they are setting a global env variable rather than prepending on the command:

https://github.com/travis-ci/worker/blob/master/.travis.yml#L20

**Comment by FiloSottile** [comment]
Thank you! Instead of using the vendored packages Travis was downloading them with `go get`. Tests were passing because gb didn't break compatibility yet, but was definitely wrong.
