### ISSUE TITLE
Compared to others?

### ISSUE THREAD

**Issue by mattfarina** [FiloSottile/gvt#2]
I'm one of the authors of [Glide](https://github.com/Masterminds/glide), a tool for managing the packages in a `vendor/` directory with the `GO15VENDOREXPERIMENT`. I'm curious how you see the two comparing and what you see gvt solving.

While I have a self interest in understanding needs, I'm curious so I can discuss the differences with people given the number of options popping up.

Thanks.

**Comment by lithammer** [comment]
Not the author. But for me it's very convenient when messing around and don't want to pollute the `GOPATH` with a bunch of temporary libs, and that it didn't require a manifest. Also, last time I tried Glide it didn't recursively add dependencies, which was a pain at times.

Basically, Glide would cover my use-case for gvt if it allowed to fetch deps without `glide.yaml` and fetched deps recursively. Though perhaps it already does that now?

**Comment by mattfarina** [comment]
@renstrom thanks for your feedback. gvt, if being based on gb-vendor, requires a config file. In it you list your dependencies, versions, and so forth. In both cases they are needed.

Glide does handle recursive retching now. Though, like gb-vendor and gvt you need a config file so you can specify things like versions. In glide we added `glide guess` that can generate a `glide.yaml` file from your source.

**Comment by lithammer** [comment]
> gvt, if being based on gb-vendor, requires a config file.

Yes, it seems you're correct. It sticks a "manifest" in the vendor directory, however unlike Glide, it doesn't require it to be present _before_ running get/fetch. Which was my real gripe I guess.

**Comment by mattfarina** [comment]
@renstrom thanks for the clarification. We've been talking about a feature like this so I'm glad that building something like that would be useful.

**Comment by FiloSottile** [comment]
Hi @mattfarina, I considered Glide before porting gb-vendor, but I think the two projects have different "philosophies".

gvt is meant to be as simple as it gets. go get for vendoring if you will. So it makes no requirement for config files (think of the manifest as a out-of-your-way receipt, a log) and adopts instead the semantics of go get ("just fetch/update this package here").

Does that answer your question?

**Comment by mattfarina** [comment]
@FiloSottile I "think" so. Let me repeat back what I think I read another way. If `go get` were to have the ability to download to the `vendor/` directory would this go away? Note, there's already a [`go get` issue to support fetching to `vendor/`](https://github.com/golang/go/issues/11726).

**Comment by FiloSottile** [comment]
That sounds correct. The other difference is that go get keeps the git/hg/svn metadata but you probably don't want that in your vendor/ folder.

I guess I would not be opposed to convenience functions like purge, past that.

**Comment by mattfarina** [comment]
@FiloSottile So, you are assuming that the projects will be vendored, that is stored in your projects VCS. That's also great to know. Some like it that way and some like to have the VCS metadata right there.

Thanks.

**Comment by FiloSottile** [comment]
The `rebuild` command in #1, coupled with two lines of `.gitignore`, easily enable the vendored-source-not-checked-in workflow. I'll document that once #1 is merged.

gvt will not help you with git submodules, however.

Feel free to close the issue if you have no other questions :)
