### ISSUE TITLE
gvt removes /tmp directory

### ISSUE THREAD

**Issue by snop-snov** [FiloSottile/gvt#20]
When I use gvt in Mac OS it works fine. But when I try to use it in docker container with Linux, gvt removes my $TMPDIR folder and then falls with error:

```
root@a3c98e82b487:/app# gvt fetch github.com/gorilla/mux
2016/02/12 09:47:19 fetching recursive dependency github.com/gorilla/context
2016/02/12 09:47:20 command "fetch" failed: mkdir /tmp/gvt-643984416: no such file or directory
```

If I use non-root user I get permission error

```
user@366435ab33cc:/app$ gvt fetch github.com/gorilla/mux
2016/02/12 09:48:53 command "fetch" failed: remove /tmp: permission denied
```

How can I use gvt in Linux?

**Comment by JimmyPettersson85** [comment]
I'm using gvt with Linux (no docker) without problems. This might be a problem with docker.
It is a serious problem if gvt removes $TMPDIR though and should definitely be looked into.

**Comment by FiloSottile** [comment]
Ah, I know what's going on. gvt will use a `/tmp/gvt-1234` folder to clone the repository, and then delete it and run `cleanPath`. `cleanPath` deletes all empty parents (intended to remove the `github.com` and `$USER` folders). Inside your Docker container, `/tmp` is empty.

This is tricky to fix right, I'll give it a try soon.

**Comment by FiloSottile** [comment]
(Meanwhile, `touch /tmp/foo` will work as a workaround.)

**Comment by FiloSottile** [comment]
@snop-snov Can you please confirm the latest version is fixed?

**Comment by snop-snov** [comment]
@FiloSottile Now it works fine, thanks!
