### ISSUE TITLE
Delete tests?

### ISSUE THREAD

**Issue by colinmarc** [FiloSottile/gvt#21]
Hi!

gvt works absolutely great, but one issue I have (with the vendoring thing in general) is that `go test ./...` runs all the vendored tests, as well. See this golang issue: https://github.com/golang/go/issues/11659

It makes sense technically, but is still surprising and unergonomic. It looks like other tools, like `govendor` work around this by filtering out the test files when it pulls in dependencies. I wonder if that approach might work for gvt?

**Comment by elithrar** [comment]
Workaround in the meantime: `go test $(go list ./... | grep -v /vendor/)`

**Comment by FiloSottile** [comment]
Thanks for the feedback! I'm not convinced it should strip by default, but it sounds like a good feature.

What would be a reasonable flag? `-t` would imply the opposite. `-scrub`? Maybe too generic. `-no-tests`? `-ignore-tests`?

Also, I guess it should be recorded in the manifest?

**Comment by colinmarc** [comment]
My vote would be to have it be the default, and have an `-include-tests` flag to pull them in. I think since gvt already filters some files (those that start with `.`), filtering some more by default wouldn't be surprising behavior. If you don't want to have it be the default, then I think `-exclude-tests` would probably be the most descriptive.

**Comment by colinmarc** [comment]
(Also, let me know what you'd like the interface to be, and I'm happy to whip up a PR =))

**Comment by FiloSottile** [comment]
Ok, I was thinking about this today and decided how to do it:
- `fetch` removes tests by default
- `-t` to include tests
- a `NoTests` field in the manifest, so that `recover` maintains backwards compatibility

Working on it now.
