### ISSUE TITLE
Ability to vendor a fork of a package 

### ISSUE THREAD

**Issue by basvanbeek** [FiloSottile/gvt#24]
I have forks of particular packages that have new features but are not yet merged with the official repositories. Since the import paths of these packages are exactly the same as the official ones and only the repository path would be different, I tried to import the origin and then update the repository paths manually in the manifest file. When running gvt update I see the repository paths being rewritten to the original repository URL so no luck.

Would be great if we can temporarily vendor forks using the gvt command line tool so we don't have to wait on the main repositories to merge the requests.

**Comment by FiloSottile** [comment]
That makes sense, but since it's not a common use case, I would not add a `fetch` option to do this.

I'll teach `update` and `restore` about `importpath != repository` so that the manifest modification you tried will work, and I'll document that.

**Comment by FiloSottile** [comment]
And done!
