### ISSUE TITLE
support to vendor packages custom file extensions

### ISSUE THREAD

**Issue by acewin** [FiloSottile/gvt#30]
gvt fetch works great with -t config option to get all tests and testdata. However, not all packages are designed with test data to be in testdata directory and I`d like to pass in a custom list of file extensions and/or paths that gvt should treat as "relevantFile" and vendor. 

I use a package that has some test config data in yaml files and i`d like to vendor those in  for the tests to pass. I have another use case with a go package using python plugins i.e go package ships with some python files that need to be vendored too. I believe my use cases are a bit unusual, but it would be great if gvt can support those.

**Comment by FiloSottile** [comment]
Would it work for you if I just added a `-a` flag that vendors everything?

**Comment by acewin** [comment]
Yes, that would work too. Everything except the `.git` directory. Thanks!
