### ISSUE TITLE
`gvt fetch` fails with mildly malformed XML at vanity urls

### ISSUE THREAD

**Issue by colinmarc** [FiloSottile/gvt#31]
https://github.com/zombiezen/go-capnproto2 has a vanity url with slightly malformed XML (I'll open an issue there in a second):

```
$ curl https://zombiezen.com/go/capnproto2
<meta name="go-import" content="zombiezen.com/go/capnproto2 git https://github.com/zombiezen/go-capnproto2">
<h1>zombiezen.com/go/capnproto2</h1>
<a href="https://github.com/zombiezen/go-capnproto2">Git Repository on GitHub</a>
```

The meta tag isn't closed, and there's no `head` or `body`, so [`parseMetaGoImports`](https://github.com/FiloSottile/gvt/blob/master/gbvendor/discovery.go#L35) fails to fetch it with an XML error:

```
$ gvt fetch zombiezen.com/go/capnproto2
2016/04/10 15:48:02 command "fetch" failed: XML syntax error on line 4: unexpected EOF
```

I'd say that's not too unreasonable, except that `go get` somehow manages to succeed, even though that method is identical to the one in the [go source](https://golang.org/src/cmd/go/discovery.go). I haven't been able to figure out why.

**Comment by FiloSottile** [comment]
Thanks for the detailed bug report and preliminary investigation!

It's golang/go@5b085482ae8792cf751371991488d29e7bd3762f and golang/go@81a4bbffbf70edd3aaa401b38eb581ad94e2288f

Fixed.
