### ISSUE TITLE
question on vendor path

### ISSUE THREAD

**Issue by davisford** [FiloSottile/gvt#37]
With a project layout like this:

```
project
├── bin
├── pkg
├── src
│   ├── foobar
```

If I step into `project` and do `gvt fetch github.com/some/dep` it generates the manifest and puts it here, as a sibling of `project/src`:

```
project
├── bin
├── pkg
├── src
│   ├── foobar
└── vendor
    ├── github.com
    └── manifest
```

That's just like the gb.io project layout -- which makes some sense b/c you said you modeled it after gb's vendor plugin.  But I'm having a helluva time getting the standard go compiler to understand this is where vendor lives.  It seems to want it not as a sibling of `src` but as a child of `src`.

The go version I am using: `go version go1.6.2 darwin/amd64`

If I try to build the project, it immediately complains that it cannot find the vendored code.  Here's an example where it cannot find the `aws-sdk-go` library:

```
$go build src/foobar/main.go 
src/utilities/keyval.go:10:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
    /Users/davisford/git/project/foobar/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
```

_NOTE_ here it is not even looking in vendor...with go 1.6 it is supposed to by default.  I have the old env variable enabled also just for kicks.  see the change below where it does look for vendor and reports it in the stack:

```
$ echo $GO15VENDOREXPERIMENT 
1
```

Now, if I just create an empty folder `project/src/vendor`....

```
$mkdir src/vendor
$ go build src/foobar/main.go
src/utilities/keyval.go:10:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
    /Users/davisford/git/project/foobar/src/vendor/github.com/aws/aws-sdk-go/aws (vendor tree)
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
    /Users/davisford/git/project/foobar/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
```

Of course it isn't found, b/c I just created an empty directory, but just the presence of `src/vendor` causes it to look, whereas if I have `vendor/` as a sibling it doesn't even try.

If I do this:

``` sh
~/go/project$ mv vendor/ src/
```

and build it works. 

So, my question is how are you getting your projects to work?  By default `gvt` seems to put the vendor dir as a sibling of the project's `$GOPATH/src`, but the go compiler seems to want vendor as a child of `$GOPATH/src/`

**Comment by FiloSottile** [comment]
Hi Davis, thanks for using gvt :)

What's happening here is that technically you are putting the vendor folder outside the GOPATH source tree `$GOPATH/src/` (see [this FAQ](https://github.com/FiloSottile/gvt#go-build-cant-find-the-vendored-package)). gvt just downloads to `$PWD/vendor` so it's your responsibility to be inside `$GOPATH/src/` when you run it.

However, more in general, I suspect you are misunderstanding the interaction between vendoring and GOPATH. Setting GOPATH to the root of your project is an old way to attain the same goal as vendoring, however with vendoring that's not needed anymore and you are supposed to use a general GOPATH, like a user-wide one, as explained in the Getting Started docs.

More in practice, what this means is that you want your GOPATH to be something like `~/go`, your project to live in `~/go/NAME` where NAME might be `github.com/davisford/foo` (or not, if you are not publishing it anyway), and have gvt create `~/go/NAME/vendor`.

Let me know if you can't get this working!

**Comment by davisford** [comment]
Thanks -- that makes sense
