### ISSUE TITLE
 Vendor folder and goxc not compatible ?

### ISSUE THREAD

**Issue by joeblew99** [FiloSottile/gvt#41]
This is not an issue with gvt, but it might be that gvt can easily adapt to this problem.

I use goxc to cross compile, and i just starting using gvt to do my vendoring, and when i tried to do a goxc compile (which was working fine the last few months) it went nuts.

It seems that others might be hitting same issue.
https://github.com/laher/goxc/issues/99

thoughts ?

**Comment by FiloSottile** [comment]
Not sure I see the issue here. Can you report exactly what breaks?

**Comment by joeblew99** [comment]
I fixed it. Nothing to do with gvt

The goxc json file needed to exclude the vendor folder like this.

 "MainDirsExclude": "./**vendor**,./_infra/dev/rethinkdb-vm/.clear,./nodes/sync"

I was using godep before :)
