### ISSUE TITLE
Readme needs to state this won't work outside the $GOPATH tree

### ISSUE THREAD

**Issue by rohanthewiz** [FiloSottile/gvt#5]
Just putting the issue up so I or someone else will update the README to state this will not work outside of the $GOPATH tree due to current restriction of GO15VENDOREXPERIMENT.

**Comment by rohanthewiz** [comment]
Pull request created: https://github.com/FiloSottile/gvt/pull/8

**Comment by FiloSottile** [comment]
Merged #8
