### ISSUE TITLE
Error: no buildable Go source files in...

### ISSUE THREAD

**Issue by jsgv** [FiloSottile/gvt#53]
Unsure if this is an issue with gvt, looking to get any feedback.

I was able to download the packages to `vendor/` folder.
`gvt fetch golang.org/x/sys`

But now I am getting the error that it can not build the packages, even though the package is there.

```
no buildable Go source files in /Users/jesus/.gvm/pkgsets/go1.6/global/src/client/theclient/thepackage/vendor/golang.org/x/sys/windows/svc/eventlog
```

![screen shot 2016-05-19 at 2 07 55 pm](https://cloud.githubusercontent.com/assets/2798097/15409943/0c5fea96-1dcc-11e6-8d1f-7a85c1976213.png)

All other packages imported with `gvt` work fine.

**Comment by FiloSottile** [comment]
Quick guess: are you building on a non-Windows machine, and do the files in that package all have a Windows-only build tag?

**Comment by jsgv** [comment]
Ahh, thanks.
And thank you for this package! Super helpful.
