### ISSUE TITLE
Add a fast "restore" command

### ISSUE THREAD

**Issue by vincentbernat** [FiloSottile/gvt#57]
Hey!

It seems that "gvt restore" will "git pull" everything unconditionally. It would be convenient to have it check if the dependency is already at the desired version and skip the "git pull". This way, "gvt restore" can be used before each compilation.

**Comment by vincentbernat** [comment]
My bad. Since each repository is a copy, the information is not here. So, not possible.

**Comment by FiloSottile** [comment]
That was quick, thanks :)
