### ISSUE TITLE
question. pulling repos that are already pulled ?

### ISSUE THREAD

**Issue by joeblew99** [FiloSottile/gvt#59]
When i pull from a github account where one repo references another, does gvt not pull the referenced repo ?

I guess it depends ?
If the first repo is using go vendoring, and it has the vendored package in its own vendored tree does it pull it ?

I am trying to work out the behaviour.

**Comment by FiloSottile** [comment]
fetch does pull missing referenced repos, but does not update existing ones.

update -recursive will update referenced repos (see #6)

if there's a vendored pkg, it's not considered an external dep, so it won't be pulled
