### ISSUE TITLE
Add support for relative imports

### ISSUE THREAD

**Issue by lcosmin** [FiloSottile/gvt#62]
Any idea why this fails (using latest gvt)?

$ gvt fetch gopkg.in/couchbaselabs/gocb.v1
2016/07/06 10:52:04 Fetching: gopkg.in/couchbaselabs/gocb.v1
2016/07/06 10:52:12 · Fetching recursive dependency: github.com/couchbase/gocb/gocbcore
2016/07/06 10:52:14 ·· Fetching recursive dependency: ./javamock
2016/07/06 10:52:14 command "fetch" failed: error fetching ./javamock: "./javamock" is not a valid import path

**Comment by 0x434d53** [comment]
Couchbase does something i hate (because it also breaks also goimports - it will always throw out your import again): They have an local import path (./imports), but the package is named different (gocbmock). Looks like gvt can't handle it.

**Comment by defcube** [comment]
[ removed an OT comment about couchbase -- @FiloSottile ]
