### ISSUE TITLE
gvt vendor dependencies that are only imported in test files (_test.go)

### ISSUE THREAD

**Issue by unders** [FiloSottile/gvt#63]
When I fetch mergo with gvt command:

`$ gvt fetch github.com/imdario/mergo`

gvt also vendor dependencies that is only imported from test files:

```
$ gvt list
github.com/imdario/mergo https://github.com/imdario/mergo master 50d4dbd4eb0e84778abe37cefef140271d96fade
gopkg.in/check.v1        https://gopkg.in/check.v1        v1     4f90aeace3a26ad7021961c297b22c42160c7b25
gopkg.in/yaml.v1         https://gopkg.in/yaml.v1         v1     9f9df34309c04878acc86042b16630b0f696e1de
```

Packages:

```
gopkg.in/check.v1 
gopkg.in/yaml.v1 
```

are only imported from a test file: [mergo_test.go](https://github.com/imdario/mergo/blob/master/mergo_test.go#L13)

gvt havn't vendored any test file and therefore shouldn't vendor any test file imported dependecies.

**Comment by FiloSottile** [comment]
Oh, yes, this is silly. Thank you!
