### ISSUE TITLE
Support relative imports

### ISSUE THREAD

**Issue by titpetric** [FiloSottile/gvt#66]
The following snippet should illustrate the problem:

```
# gvt fetch  "github.com/robertkrimen/otto"
2016/07/21 13:07:04 Fetching: github.com/robertkrimen/otto
2016/07/21 13:07:09 · Fetching recursive dependency: ./terst
2016/07/21 13:07:09 command "fetch" failed: error fetching ./terst: "./terst" is not a valid import path
```

It should be imported from github.com/robertkrimen/otto/terst. I know they will not work with vendoring afterwards, but I'm not beyond hacking a few import lines on whatever gets downloaded. ;)

**Comment by titpetric** [comment]
Or, perhaps exclude `*_test.go` - is there a reason that tests should be part of the vendored package?

**Comment by FiloSottile** [comment]
The tests part was #63

**Comment by FiloSottile** [comment]
The rest is a duplicate of #62
