### ISSUE TITLE
Parallelize `gvt rebuild`

### ISSUE THREAD

**Issue by petrkotek** [FiloSottile/gvt#7]
Fetching of all dependencies can take relatively long time (couple of minutes or more). It may be possible to speed it up by running several `git fetch` calls in parallel.

What do you think? Is there any reason why not to do it?

(If you think it's a good idea, i can give it a shot)

**Comment by rayward** [comment]
:+1:

**Comment by ryanking** [comment]
:+1:

**Comment by petrkotek** [comment]
PR open (https://github.com/FiloSottile/gvt/issues/10); waiting for feedback from the package maintainer(s)

**Comment by FiloSottile** [comment]
Fixed by @petrkotek in #10
