### ISSUE TITLE
correctness: fetched dependencies missing their git submodules

### ISSUE THREAD

**Issue by dt** [FiloSottile/gvt#81]
What I did:
```
gvt fetch github.com/dt/subparentdemo
```

What I expected:
```
$ ls vendor/github.com/dt/subparentdemo/subdemo
lib.go
```

What happened:
```
$ ls vendor/github.com/dt/subparentdemo/subdemo
ls: vendor/github.com/dt/subparentdemo/subdemo: No such file or directory
```

http://github.com/dt/subparentdemo here is a little dummy library that relies on subpackage (`subdemo`) that it pulls in via a git submodule. `subparentdemo ` works fine when `go get`ed, since `go get` runs `submodule update --init` after cloning.

**Comment by sdboyer** [comment]
if/when y'all do want to try to take a stab at this one, what i did in Masterminds/vcs#60 might be a useful reference

**Comment by dt** [comment]
fwiw, I also have a PR open that init's submodules: https://github.com/FiloSottile/gvt/pull/82
