### ISSUE TITLE
Ability to download private repos from github

### ISSUE THREAD

**Issue by alex-tan** [FiloSottile/gvt#9]
When gvt fetching a private repo, I get the usual prompt:

Username for 'https://github.com':
Password for `...`:

Is there a way to use ssh keys to fetch the repos?

**Comment by canthefason** [comment]
I updated my git config as this, and now it is working for private repos: 

```
git config --global url."git@github.com:".insteadOf https://github.com/
```

**Comment by alex-tan** [comment]
@canthefason worked for me. Thanks!
